version: "2"

services:
  webapp:
    build: .
    ports:
        - "8080:8080"
    links:
        - influxdb
  influxdb:
    image: influxdb:alpine
    ports:
        - "8083:8083"
        - "8086:8086"
    volumes:
        - ./influxdb/data:/var/lib/influxdb
    environment:
        - INFLUXDB_ADMIN_ENABLED=true
